# Multiclass SVM 구현

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [4]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [5]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.

In [6]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.

In [7]:
# ["setosa", "versicolor", "virginica"] 순서
not_set = y_train[y_train != "setosa"] # 0/1
not_ver = y_train[y_train != "versicolor"] # 0/2
not_vir = y_train[y_train != "virginica"] # 1/2

In [8]:
# one-hot encoding
y_not_set = pd.get_dummies(not_set, drop_first=True, columns="isVirginica") # 2번 꽃인지 1번 꽃인지 파악
y_not_ver = pd.get_dummies(not_ver, drop_first=True, columns="isVersicolor") # 2번 꽃인지 0번 꽃인지 파악
y_not_vir = pd.get_dummies(not_vir, drop_first=True, columns="isSetosa") # 1번 꽃인지 0번 꽃인지 파악

In [9]:
svm_1_OVO = SVC(kernel ='rbf', C = 5, gamma = 5) # 0 vs 1
svm_2_OVO = SVC(kernel ='rbf', C = 5, gamma = 5) # 0 vs 2
svm_3_OVO = SVC(kernel ='rbf', C = 5, gamma = 5) # 1 vs 2

In [10]:
# 학습을 위한 X 데이터 생성
x_not_set = X_train[y_train != "setosa"]
x_not_ver = X_train[y_train != "versicolor"]
x_not_vir = X_train[y_train != "virginica"]

In [11]:
svm_1_OVO.fit(x_not_vir, y_not_vir) # 0 vs 1
svm_2_OVO.fit(x_not_ver, y_not_ver) # 0 vs 2
svm_3_OVO.fit(x_not_set, y_not_set) # 1 vs 2

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(C=5, gamma=5)

In [12]:
svm_1_OVO.predict(X_test) #  1번 꽃으로 예측하면 1, 0번 꽃으로 예측하면 0을 반환한다.

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1], dtype=uint8)

In [13]:
svm_2_OVO.predict(X_test) # 2번 꽃으로 예측하면 1, 0번 꽃으로 예측하면 0을 반환한다.

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1], dtype=uint8)

In [14]:
svm_3_OVO.predict(X_test) #  2번 꽃으로 예측하면 1, 1번 꽃으로 예측하면 0을 반환한다.

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0], dtype=uint8)

## One vs One SVM

In [17]:
def one_one_svm_predict(models, data, labels):
    result = []
    
    for model in models: 
        pred = model.predict(data)
        result.append(pred)
    
    result = np.array(result).T 
    '''
    result 배열의 구성은 다음과 같다.
    row : x_test 데이터 한 개에 대한 예측값
    col : 순서대로
    [1번 0번 예측기 (1번일때 1반환), 2번 0번 예측기(2번일때 1반환), 2번 1번 예측기(2번일 때 1 반환)]
    ''' 
    
    pred = []

    for row in range(len(result)):
        score = np.array([0, 0, 0])
        

        if result[row][0] == 1: # 1번 꽃
            score[1] += 1
        elif result[row][0] == 0: # 0번 꽃
            score[0] += 1
            
        if result[row][1] == 1: # 2번 꽃
            score[2] += 1
        elif result[row][1] == 0: # 0번 꽃
            score[0] += 1
            
        if result[row][2] == 1: # 2번 꽃
            score[2] += 1
        elif result[row][2] == 0: # 1번 꽃
            score[1] += 1
    
        pred.append(labels[score.argmax()]) #  꽃 이름으로 바꿔서 append
    
    
    print(f"prediction : \n {result}")
    
    return pred
    
    
models = [svm_1_OVO, svm_2_OVO, svm_3_OVO]
labels = ["setosa", "versicolor", "virginica"]           

In [18]:
odels = [svm_1_OVO, svm_2_OVO, svm_3_OVO]
labels = ["setosa", "versicolor", "virginica"]

prediction = one_one_svm_predict(models, X_test, labels)
accuracy_score(y_test,prediction)

prediction : 
 [[1 1 0]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [0 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]]


0.8666666666666667